### ISSUE TITLE
Reveal.js A11y Plugin: Offscreen slides hidden in "overview mode"

### ISSUE THREAD

**Issue by marcysutton** [marcysutton/gdi-web-accessibility#1]
Overview mode is broken with the Accessibility Plugin, because offscreen slides are still fully hidden. Fix: Look for a framework hook when overview mode opens to temporarily disable the CSS hiding offscreen slides. 
<img width="667" alt="GDI Sass curriculum" src="https://cloud.githubusercontent.com/assets/1045233/9281440/f6235304-4279-11e5-9fae-f87ecc867ae1.png">

**Comment by marcysutton** [comment]
That color contrast is also terrible, but that's a separate issue...

**Comment by Roenok** [comment]
I did a check, and it's 3.3:1 for a headings, so within WCAG 2.0 Level AA. We could probably stand to darken it a little bit, though.
